name: 'Install Energyplus'
description: 'Installs EnergyPlus'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


inputs:
  energyplus-version:
    description: 'EnergyPlus major.minor.patch version'
    required: true
    default: 9.2.0
  energyplus-sha:
    description: 'EnergyPlus version SHA'
    required: true
    default: 921312fa1d
  energyplus-install:
    description: 'EnergyPlus major-minor-patch version'
    default: 9-2-0
    required: true
  
runs:
  using: "composite"
  steps:
    - run: echo Installing EnergyPlusV${{ inputs.energyplus-version }}...
      shell: bash
    - run: echo "${{ github.action_path }}" >> ${{ github.workspace }} 
      shell: bash
    - run: install.sh
      shell: bash
      env:
        ENERGYPLUS_VERSION: ${{ inputs.energyplus-version }}
        ENERGYPLUS_SHA: ${{ inputs.energyplus-sha }}
        ENERGYPLUS_INSTALL_VERSION: ${{ inputs.energyplus-install }}
