env: {energyplus-install: 23-2-0, energyplus-sha: 7636e6b3e9, energyplus-version: 23.2.0,
  ubuntu-version: 20.04}
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - {uses: actions/checkout@v3}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with: {python-version: '${{ matrix.python-version }}'}
    - {name: Install dependencies, run: 'python -m pip install --upgrade pip

        python -m pip install pytest

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        '}
    - {run: 'echo see the dict ${{ env.energyplus-version }} here', shell: bash}
    - {run: 'echo Installing EnergyPlusV${{ github.event }}...', shell: bash}
    - {run: 'echo "${{ github.action_path }}" >> $GITHUB_PATH', shell: bash}
    - env: {ENERGYPLUS_INSTALL_VERSION: '${{ env.energyplus-install }}', ENERGYPLUS_SHA: '${{
          env.energyplus-sha }}', ENERGYPLUS_VERSION: '${{ env.energyplus-version
          }}', UBUNTU_VERSION: '${{ env.ubuntu-version }}'}
      run: 'echo "In YML $ENERGYPLUS_VERSION"

        echo "In YML $ENERGYPLUS_SHA"

        echo "In YML $ENERGYPLUS_INSTALL_VERSION"

        echo "In YML $UBUNTU_VERSION"

        bash .github/workflows/install.sh

        '
      shell: bash
    - {name: Test with pytest, run: 'pytest

        '}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
name: eppy package
on:
  push:
    branches: [main, i1_epversion]
